labels:
  # The `solved` label is added to discussions
  fixed:
    issues:
      # Post a comment, `{issue-author}` is an optional placeholder
      comment: >
        :wave: @{issue-author}, please use our idea board to request new features.
      close: true
